services:
  - type: web
    name: nahel-hakol
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NITRO_PRESET
        value: node-server
      - key: NODE_VERSION
        value: 22
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
