/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BirthdaysRouteImport } from './routes/birthdays'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as EventNewRouteImport } from './routes/event.new'
import { Route as ExpenseNewRouteImport } from './routes/expense.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdaysRoute = BirthdaysRouteImport.update({
  id: '/birthdays',
  path: '/birthdays',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const EventNewRoute = EventNewRouteImport.update({
  id: '/event/new',
  path: '/event/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseNewRoute = ExpenseNewRouteImport.update({
  id: '/expense/new',
  path: '/expense/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/birthdays': typeof BirthdaysRoute
  '/calendar': typeof CalendarRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shopping': typeof ShoppingRoute
  '/tasks': typeof TasksRoute
  '/event/new': typeof EventNewRoute
  '/expense/new': typeof ExpenseNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/birthdays': typeof BirthdaysRoute
  '/calendar': typeof CalendarRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shopping': typeof ShoppingRoute
  '/tasks': typeof TasksRoute
  '/event/new': typeof EventNewRoute
  '/expense/new': typeof ExpenseNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/birthdays': typeof BirthdaysRoute
  '/calendar': typeof CalendarRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shopping': typeof ShoppingRoute
  '/tasks': typeof TasksRoute
  '/event/new': typeof EventNewRoute
  '/expense/new': typeof ExpenseNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/birthdays'
    | '/calendar'
    | '/finance'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/shopping'
    | '/tasks'
    | '/event/new'
    | '/expense/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/birthdays'
    | '/calendar'
    | '/finance'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/shopping'
    | '/tasks'
    | '/event/new'
    | '/expense/new'
  id:
    | '__root__'
    | '/'
    | '/birthdays'
    | '/calendar'
    | '/finance'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/shopping'
    | '/tasks'
    | '/event/new'
    | '/expense/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BirthdaysRoute: typeof BirthdaysRoute
  CalendarRoute: typeof CalendarRoute
  FinanceRoute: typeof FinanceRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShoppingRoute: typeof ShoppingRoute
  TasksRoute: typeof TasksRoute
  EventNewRoute: typeof EventNewRoute
  ExpenseNewRoute: typeof ExpenseNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthdays': {
      id: '/birthdays'
      path: '/birthdays'
      fullPath: '/birthdays'
      preLoaderRoute: typeof BirthdaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/new': {
      id: '/event/new'
      path: '/event/new'
      fullPath: '/event/new'
      preLoaderRoute: typeof EventNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense/new': {
      id: '/expense/new'
      path: '/expense/new'
      fullPath: '/expense/new'
      preLoaderRoute: typeof ExpenseNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BirthdaysRoute: BirthdaysRoute,
  CalendarRoute: CalendarRoute,
  FinanceRoute: FinanceRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShoppingRoute: ShoppingRoute,
  TasksRoute: TasksRoute,
  EventNewRoute: EventNewRoute,
  ExpenseNewRoute: ExpenseNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
